### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/connector-jira#87]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] connector_jira
- [ ] connector_jira_servicedesk
- [ ] connector_jira_tempo
- [ ] connector_jira_tempo_base
- [ ] server_env_connector_jira

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by yboujraf** [comment]
Dear @sbidoul 

Any idea if the jira module for cloud will be migrated in 16.0 ?

Best Regards
